import dotenv from 'dotenv';

dotenv.config();

export const env = {
  serverVersion: '1.1.0',
  nodeEnv: process.env.NODE_ENV || 'development',
  port: Number(process.env.PORT || 5000),
  corsOrigin: process.env.CORS_ORIGIN || '*',
  mongodbUri: process.env.MONGODB_URI || '',
  masterDbName: process.env.MASTER_DB_NAME || 'master',
  anthropicApiKey: process.env.ANTHROPIC_API_KEY || '',
  langgraphChatEnabled: String(process.env.LANGGRAPH_CHAT_ENABLED || '').toLowerCase() === 'true',
  langgraphChatModel: process.env.LANGGRAPH_CHAT_MODEL || '',
  langgraphUnderstandTimeoutMs: Number(process.env.LANGGRAPH_UNDERSTAND_TIMEOUT_MS || 45000),
  langgraphMaxTokens: Number(process.env.LANGGRAPH_MAX_TOKENS || 4096),
  langgraphUseLlmContinuation: String(process.env.LANGGRAPH_USE_LLM_CONTINUATION || '').toLowerCase() === 'true',
  langgraphDbName: process.env.LANGGRAPH_DB_NAME || process.env.MASTER_DB_NAME || 'master',
  langgraphCheckpointTtlSeconds: Number(
    process.env.LANGGRAPH_CHECKPOINT_TTL_SECONDS || 60 * 60 * 24 * 30,
  ),
  langsmithTracing: String(process.env.LANGSMITH_TRACING || '').toLowerCase() === 'true',
  langsmithApiKey: process.env.LANGSMITH_API_KEY || '',
  langsmithProject: process.env.LANGSMITH_PROJECT || 'agent-customer',
  langsmithTags: String(process.env.LANGSMITH_TAGS || '')
    .split(',')
    .map((tag) => tag.trim())
    .filter(Boolean),

  logLevel: process.env.LOG_LEVEL || 'info',
  developerMonitorKey: process.env.DEVELOPER_MONITOR_KEY || '',
  checkBotUserIdUrl: process.env.CHECK_BOT_USERID || '',
  guestUserStatusUrl: process.env.GUEST_USER_STATUS_URL || 'https://admin.cybot.world/getGuestUserStatusBasedOnTaskId',
  getbotDetails: process.env.GET_BOT_DETAILS || '',
  addBotAsBuddyUrl: process.env.ADD_BOT_BUDDY || '',
  createBotTaskUrl: process.env.CREATE_BOT_TASK || '',
  deleteBotTaskUrl: process.env.DELETE_BOT_TASK || '',
  reassignBotTaskUrl: process.env.REASSIGN_BOT_TASK || '',
  getBotTaskUrl: process.env.GET_BOT_TASK || '',
  sentToQuestionUrl: process.env.SENT_TO_QUESTION || '',
  userCheckPhoneNumberSuffix: process.env.USER_CHECK_PHONE_NUMBER_SUFFIX || '_CyBot_WORLD',
  botDbName: process.env.BOT_DB_NAME || '',
  widgetBaseUrl: process.env.WIDGET_BASE_URL || 'https://widget.cybot.world',
  widgetAiAssistantDetailsPath: process.env.WIDGET_AI_ASSISTANT_DETAILS_PATH || 'ai-assistant/ai-assist-details',
  widgetBrandType: process.env.WIDGET_BRAND_TYPE || 'cybot',
  standardEoFromServer: process.env.STANDARD_EO_FROM_SERVER || 'FSMAGENT',
  entitlementsBaseUrl: process.env.ENTITLEMENTS_BASE_URL || '',
  entitlementsAvailabilityUrl: process.env.ENTITLEMENTS_AVAILABILITY_URL || '',
  entitlementsConsumeCsmAgentUrl: process.env.ENTITLEMENTS_CONSUME_CSM_AGENT_URL || '',
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
  awsRegion: process.env.AWS_REGION || 'us-east-1',
  awsS3Bucket: process.env.AWS_S3_BUCKET || '',
  awsS3Prefix: process.env.AWS_S3_PREFIX || '',
  s3StorageFolder: process.env.S3_STORAGE_FOLDER || '',
  s3ApiUrl: process.env.S3_API_URL || '',
  clientUrl: process.env.CLIENT_URL || '',
  productOrderClientUrl: process.env.PRODUCT_ORDER_CLIENT_URL || process.env.CLIENT_URL || '',
  kafkaMsgUrlWs: process.env.KAFKA_MSG_URL_WS || '',
  ivrInquiryAgentUrl: process.env.IVR_INQUIRY_AGENT_URL || '',
  ivrOrderAgentUrl: process.env.IVR_ORDER_AGENT_URL || '',
  ivrInterruptCallAndContinueViaWidgetUrl:
    process.env.IVR_INTERRUPT_CALL_AND_CONTINUE_VIA_WIDGET_URL ||
    'https://cybotone.cybot.world/ivr/interruptCallAndContinueViaWidget',
  cybotPhoneSmsService: process.env.CYBOT_PHONE_SMS_SERVICE || '',
  ivrSmsSendEnabled: String(process.env.IVR_SMS_SEND_ENABLED || 'false').toLowerCase() === 'true',
  zohoClientId: process.env.ZOHO_CLIENT_ID || '',
  zohoClientSecret: process.env.ZOHO_CLIENT_SECRET || '',
  zohoOrgId: process.env.ZOHO_ORG_ID || '',
  zohoRedirectUri: process.env.ZOHO_REDIRECT_URI || '',
  zohoFrontendCallbackPath: process.env.ZOHO_FRONTEND_CALLBACK_PATH || '/zoho/callback',
  zohoAccountsUrl: process.env.ZOHO_ACCOUNTS_URL || 'https://accounts.zoho.com',
  zohoScope: process.env.ZOHO_SCOPE || '',
};
