export const MASTER_DATA_CUSTOMERS_COLLECTION = 'md_customers';

export const masterDataCustomerCollectionSchema = {
  bsonType: 'object',
  required: ['tenantId', 'botUserId', 'displayName', 'status', 'isDeleted', 'createdAt', 'updatedAt'],
  additionalProperties: true,
  properties: {
    tenantId: { bsonType: 'string' },
    botUserId: { bsonType: 'string' },
    customerCode: { bsonType: ['string', 'null'] },
    tierId: { bsonType: ['objectId', 'null'] },
    customerType: { bsonType: 'string' },
    displayName: { bsonType: 'string' },
    companyName: { bsonType: ['string', 'null'] },
    email: { bsonType: ['string', 'null'] },
    phoneCountryCode: { bsonType: ['string', 'null'] },
    phone: { bsonType: ['string', 'null'] },
    mobileCountryCode: { bsonType: ['string', 'null'] },
    mobile: { bsonType: ['string', 'null'] },
    cybotUserId: { bsonType: ['string', 'null'] },
    isCybotRegister: { bsonType: 'bool' },
    gstNumber: { bsonType: ['string', 'null'] },
    taxTreatment: { bsonType: ['string', 'null'] },
    billingAddress: { bsonType: 'string' },
    shippingAddress: { bsonType: ['string', 'null'] },
    currencyCode: { bsonType: ['string', 'null'] },
    paymentTerms: { bsonType: ['string', 'null'] },
    status: { bsonType: 'string' },
    isDeleted: { bsonType: 'bool' },
    zohoCustomerId: { bsonType: ['string', 'null'] },
    zohoSyncStatus: { bsonType: 'string' },
    zohoLastSyncedAt: { bsonType: ['date', 'null'] },
    zohoErrorMessage: { bsonType: ['string', 'null'] },
    createdAt: { bsonType: 'date' },
    updatedAt: { bsonType: 'date' },
  },
};
