export const MASTER_DATA_INVENTORY_COLLECTION = 'md_inventory';

export const masterDataInventoryCollectionSchema = {
  bsonType: 'object',
  required: ['tenantId', 'botUserId', 'sku', 'itemName', 'category', 'isActive', 'isDeleted', 'createdAt', 'updatedAt'],
  additionalProperties: true,
  properties: {
    tenantId: { bsonType: 'string' },
    botUserId: { bsonType: 'string' },
    sku: { bsonType: 'string' },
    normalizedSku: { bsonType: ['string', 'null'] },
    productName: { bsonType: ['string', 'null'] },
    itemName: { bsonType: 'string' },
    category: { bsonType: 'string' },
    description: { bsonType: ['string', 'null'] },
    color: { bsonType: ['string', 'null'] },
    finish: { bsonType: ['string', 'null'] },
    doorType: { bsonType: ['string', 'null'] },
    glassDoor: { bsonType: ['bool', 'null'] },
    sellingPrice: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    salesPrice: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    currency: { bsonType: ['string', 'null'] },
    quantity: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    qtyAvailable: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    unit: { bsonType: ['string', 'null'] },
    generalSku: { bsonType: ['string', 'null'] },
    style: { bsonType: ['string', 'null'] },
    width: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    height: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    depth: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    dimensionSignature: { bsonType: ['string', 'null'] },
    dimensionAliases: {
      bsonType: ['array', 'null'],
      items: { bsonType: 'string' },
    },
    normalizedSearchText: { bsonType: ['string', 'null'] },
    restockLeadTimeDays: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    reorderLevel: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    active: { bsonType: ['bool', 'null'] },
    purchasePrice: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    isActive: { bsonType: 'bool' },
    leadTimeDays: { bsonType: ['double', 'int', 'long', 'decimal', 'null'] },
    notes: { bsonType: ['string', 'null'] },
    sourceFileName: { bsonType: ['string', 'null'] },
    importBatchId: { bsonType: ['string', 'null'] },
    lastImportedAt: { bsonType: ['date', 'null'] },
    isDeleted: { bsonType: 'bool' },
    createdAt: { bsonType: 'date' },
    updatedAt: { bsonType: 'date' },
  },
};
