export const MASTER_DATA_WORK_ORDERS_COLLECTION = 'md_work_orders';

export const masterDataWorkOrderCollectionSchema = {
  bsonType: 'object',
  required: [
    'tenantId',
    'botUserId',
    'workOrderNumber',
    'customerId',
    'status',
    'paymentStatus',
    'deliveryMode',
    'isDeleted',
    'createdAt',
    'updatedAt',
  ],
  additionalProperties: true,
  properties: {
    tenantId: { bsonType: 'string' },
    botUserId: { bsonType: 'string' },
    orderSource: { bsonType: ['string', 'null'] },
    workOrderNumber: { bsonType: 'string' },
    salesOrderId: { bsonType: 'string' },
    customerId: { bsonType: 'objectId' },
    quoteId: { bsonType: ['objectId', 'null'] },
    invoiceId: { bsonType: ['objectId', 'null'] },
    paymentIds: {
      bsonType: 'array',
      items: { bsonType: 'objectId' },
    },
    branchId: { bsonType: ['string', 'null'] },
    status: { bsonType: 'string' },
    paymentStatus: { bsonType: 'string' },
    dispatchStatus: { bsonType: ['string', 'null'] },
    pickupStatus: { bsonType: ['string', 'null'] },
    deliveryMode: { bsonType: 'string' },
    requestedAt: { bsonType: ['date', 'null'] },
    requestedLocalDateTime: { bsonType: ['string', 'null'] },
    requestedLocalTimeZone: { bsonType: ['string', 'null'] },
    quoteAcceptedAt: { bsonType: ['date', 'null'] },
    invoiceCreatedAt: { bsonType: ['date', 'null'] },
    paymentCompletedAt: { bsonType: ['date', 'null'] },
    productionStartedAt: { bsonType: ['date', 'null'] },
    readyForDispatchAt: { bsonType: ['date', 'null'] },
    dispatchedAt: { bsonType: ['date', 'null'] },
    pickedUpAt: { bsonType: ['date', 'null'] },
    closedAt: { bsonType: ['date', 'null'] },
    cancelledAt: { bsonType: ['date', 'null'] },
    cancellationReason: { bsonType: ['string', 'null'] },
    autoCancelledAfterDays: { bsonType: ['int', 'long', 'null'] },
    totalAmount: { bsonType: ['number', 'null'] },
    paidAmount: { bsonType: ['number', 'null'] },
    balanceAmount: { bsonType: ['number', 'null'] },
    creditAmountAddedBack: { bsonType: ['number', 'null'] },
    customerRequestNotes: { bsonType: ['string', 'null'] },
    internalNotes: { bsonType: ['string', 'null'] },
    lineItems: { bsonType: 'array' },
    taskSummary: {
      bsonType: ['object', 'null'],
      properties: {
        totalTasks: { bsonType: ['int', 'long', 'null'] },
        pendingTasks: { bsonType: ['int', 'long', 'null'] },
        inProgressTasks: { bsonType: ['int', 'long', 'null'] },
        completedTasks: { bsonType: ['int', 'long', 'null'] },
        cancelledTasks: { bsonType: ['int', 'long', 'null'] },
      },
    },
    statusTimeline: {
      bsonType: 'array',
      items: {
        bsonType: 'object',
        properties: {
          status: { bsonType: 'string' },
          changedAt: { bsonType: 'date' },
          changedBy: { bsonType: ['string', 'null'] },
          notes: { bsonType: ['string', 'null'] },
        },
      },
    },
    s3Documents: {
      bsonType: ['object', 'null'],
      properties: {
        quote: {
          bsonType: ['object', 'null'],
          properties: {
            bucket: { bsonType: ['string', 'null'] },
            region: { bsonType: ['string', 'null'] },
            folderName: { bsonType: ['string', 'null'] },
            fileName: { bsonType: ['string', 'null'] },
            fileNameFolder: { bsonType: ['string', 'null'] },
            mimeType: { bsonType: ['string', 'null'] },
            contentType: { bsonType: ['string', 'null'] },
            key: { bsonType: ['string', 'null'] },
            url: { bsonType: ['string', 'null'] },
            uploadedAt: { bsonType: ['date', 'null'] },
          },
        },
        invoice: {
          bsonType: ['object', 'null'],
          properties: {
            bucket: { bsonType: ['string', 'null'] },
            region: { bsonType: ['string', 'null'] },
            folderName: { bsonType: ['string', 'null'] },
            fileName: { bsonType: ['string', 'null'] },
            fileNameFolder: { bsonType: ['string', 'null'] },
            mimeType: { bsonType: ['string', 'null'] },
            contentType: { bsonType: ['string', 'null'] },
            key: { bsonType: ['string', 'null'] },
            url: { bsonType: ['string', 'null'] },
            uploadedAt: { bsonType: ['date', 'null'] },
          },
        },
      },
    },
    isDeleted: { bsonType: 'bool' },
    createdAt: { bsonType: 'date' },
    updatedAt: { bsonType: 'date' },
  },
};
